/* ============================================================
   inno4te Networking Academy — Question Bank v2
   200+ exam-accurate questions | Domain-tagged for score breakdown
   Pass thresholds: CCNA 82% | Network+ 72% | Security+ 75%
   ============================================================ */
(function(){
"use strict";
window.QUESTION_BANK = {

/* ────────────────────────────────────────────────────────────
   NETWORKING FUNDAMENTALS  (30 questions)
   ──────────────────────────────────────────────────────────── */
fundamentals:[
  {q:"Which layer of the OSI model is responsible for logical IP addressing and routing between networks?",opts:["Layer 2 – Data Link","Layer 3 – Network","Layer 4 – Transport","Layer 5 – Session"],a:1,d:"OSI Model",exp:"Layer 3 (Network) handles logical addressing (IP) and routing. Layer 2 handles MAC addressing. Layer 4 handles end-to-end connections."},
  {q:"In the TCP/IP model, which layer corresponds to BOTH the Session and Presentation layers of the OSI model?",opts:["Network Access","Internet","Transport","Application"],a:3,d:"OSI Model",exp:"The TCP/IP Application layer maps to OSI layers 5 (Session), 6 (Presentation) and 7 (Application). TCP/IP has only 4 layers."},
  {q:"A switch receives a frame with an unknown destination MAC address. What action does it take?",opts:["Drops the frame silently","Sends it to the default gateway","Floods it out all ports except the source port","Sends an ARP request"],a:2,d:"Switching",exp:"This is called 'unknown unicast flooding'. The switch floods the frame so the destination can respond, at which point it learns the MAC–port mapping."},
  {q:"What is the purpose of the ARP protocol?",opts:["Resolve domain names to IP addresses","Resolve IP addresses to MAC addresses","Assign IPs dynamically","Encrypt data at Layer 2"],a:1,d:"Protocols",exp:"ARP (Address Resolution Protocol) maps a known IPv4 address to its corresponding MAC address so a device can build a valid Layer 2 frame."},
  {q:"Which of the following is NOT a private (RFC 1918) IP address range?",opts:["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16","172.32.0.0/16"],a:3,d:"IP Addressing",exp:"RFC 1918 private ranges: 10.0.0.0/8, 172.16.0.0–172.31.255.255 (/12), and 192.168.0.0/16. 172.32.0.0 is public."},
  {q:"Which transport layer protocol provides reliable, connection-oriented delivery?",opts:["UDP","ICMP","TCP","GRE"],a:2,d:"Protocols",exp:"TCP (option 2) provides reliable, connection-oriented delivery using a 3-way handshake, sequence numbers, and acknowledgements. UDP is connectionless and faster but unreliable."},
  {q:"What does the DHCP DORA process stand for?",opts:["Discover, Order, Request, Acknowledge","Discover, Offer, Request, Acknowledge","Define, Offer, Route, Assign","Discover, Offer, Route, Acknowledge"],a:1,d:"Protocols",exp:"DORA: The client broadcasts a Discover, the server replies with an Offer, the client sends a Request, and the server confirms with an Acknowledge."},
  {q:"Which protocol uses port 53 for both TCP and UDP?",opts:["DHCP","DNS","SNMP","NTP"],a:1,d:"Protocols",exp:"DNS uses UDP/53 for standard queries (fast) and TCP/53 for zone transfers or responses >512 bytes."},
  {q:"What is the loopback address in IPv4?",opts:["0.0.0.0","255.255.255.255","127.0.0.1","169.254.0.1"],a:2,d:"IP Addressing",exp:"127.0.0.1 (the /8 range 127.0.0.0–127.255.255.255) is reserved for loopback. Traffic sent there never leaves the host — used for self-testing."},
  {q:"How many usable host addresses are in a /28 subnet?",opts:["14","16","30","12"],a:0,d:"Subnetting",exp:"/28 = 4 host bits → 2^4 = 16 total addresses − 2 (network + broadcast) = 14 usable hosts."},
  {q:"Which ICMP message type does the 'ping' command use?",opts:["Type 0 – Echo Reply only","Type 8 – Echo Request and Type 0 – Echo Reply","Type 3 – Destination Unreachable","Type 11 – Time Exceeded"],a:1,d:"Protocols",exp:"ping sends ICMP Type 8 Echo Requests; the remote host responds with Type 0 Echo Replies. Type 3 = unreachable, Type 11 = TTL expired (used by traceroute)."},
  {q:"What is the APIPA range assigned when a DHCP server is unreachable?",opts:["10.0.0.0/8","169.254.0.0/16","172.16.0.0/12","192.0.2.0/24"],a:1,d:"IP Addressing",exp:"APIPA (Automatic Private IP Addressing) assigns 169.254.x.x addresses when DHCP fails, allowing link-local communication but no internet routing."},
  {q:"At which OSI layer does a router primarily operate?",opts:["Layer 1","Layer 2","Layer 3","Layer 4"],a:2,d:"OSI Model",exp:"Routers operate at Layer 3 (Network), forwarding packets based on IP addresses and routing tables. They separate broadcast domains."},
  {q:"What is the default subnet mask for a Class B address?",opts:["255.0.0.0","255.255.0.0","255.255.255.0","255.255.255.128"],a:1,d:"IP Addressing",exp:"Class B ranges are 128.0.0.0–191.255.255.255 with a /16 (255.255.0.0) default mask, giving 65,534 hosts per network."},
  {q:"Which protocol maps IPv6 addresses to MAC addresses (replacing ARP for IPv6)?",opts:["ICMPv6 Neighbor Discovery (NDP)","DHCPv6","ARP for IPv6","RARP"],a:0,d:"IPv6",exp:"IPv6 uses Neighbor Discovery Protocol (NDP) via ICMPv6 for address resolution — equivalent to ARP in IPv4. It also handles router discovery."},
  {q:"What does TTL stand for and what is its purpose?",opts:["Time To Live — limits packet lifetime to prevent routing loops","Total Transfer Length — measures packet size","Type Transfer Layer — defines protocol type","Time To Locate — DNS lookup timeout"],a:0,d:"Protocols",exp:"TTL is decremented by 1 at each router hop. When it reaches 0 the packet is discarded and an ICMP Time Exceeded message is sent back."},
  {q:"Which cable is typically used to directly connect two switches together?",opts:["Straight-through","Rollover","Crossover (or auto-MDIX)","Coaxial"],a:2,d:"Physical Layer",exp:"Traditionally, a crossover cable is needed to connect like devices (switch-switch, PC-PC). Modern equipment with auto-MDIX detects and adjusts automatically."},
  {q:"In a TCP three-way handshake, what is the correct sequence of flags?",opts:["SYN → ACK → FIN","SYN → SYN-ACK → ACK","SYN-ACK → ACK → SYN","ACK → SYN → FIN"],a:1,d:"Protocols",exp:"Client sends SYN, server responds SYN-ACK, client confirms with ACK. Connection is then established. Closing uses FIN-ACK exchange."},
  {q:"What is the primary difference between a hub and a switch?",opts:["A hub is faster","A switch forwards frames only to the intended destination port; a hub sends to all ports","A hub uses IP addressing; a switch uses MAC addressing","They are functionally identical"],a:1,d:"Switching",exp:"A hub (Layer 1) repeats all signals to every port, creating collisions. A switch (Layer 2) learns MAC addresses and forwards frames only to the correct port."},
  {q:"What does QoS stand for and what does it do?",opts:["Quality of Security — encrypts traffic","Quality of Service — prioritizes certain traffic types for reliability","Quantity of Streams — limits connections","Queue of Signals — buffers packets"],a:1,d:"Protocols",exp:"QoS classifies and prioritizes traffic (e.g., VoIP over file downloads) ensuring latency-sensitive applications get bandwidth even under congestion."},
  {q:"Which IPv6 address type is equivalent to the IPv4 broadcast?",opts:["Unicast","Anycast","Multicast","There is no IPv6 broadcast — multicast is used instead"],a:3,d:"IPv6",exp:"IPv6 has no broadcast. Instead, it uses multicast to the All-Nodes multicast address (FF02::1) and All-Routers (FF02::2) for similar functions."},
  {q:"What is the maximum segment length for Gigabit Ethernet over Cat5e/Cat6 UTP?",opts:["50m","100m","150m","300m"],a:1,d:"Physical Layer",exp:"Standard Ethernet over UTP (1000BASE-T and below) has a maximum segment length of 100 metres. Beyond this, signal degradation causes errors."},
  {q:"What does DNS stand for, and which record type maps a hostname to an IPv4 address?",opts:["Domain Name System — A record","Distributed Name Service — AAAA record","Dynamic Name Server — PTR record","Domain Network Service — CNAME record"],a:0,d:"Protocols",exp:"DNS = Domain Name System. An A record maps hostname → IPv4. AAAA maps hostname → IPv6. PTR is reverse lookup. CNAME is an alias."},
  {q:"Which layer of the OSI model is responsible for establishing, managing and terminating sessions between applications?",opts:["Layer 4 – Transport","Layer 5 – Session","Layer 6 – Presentation","Layer 7 – Application"],a:1,d:"OSI Model",exp:"Layer 5 (Session) manages dialogues between endpoints — opening, maintaining and closing sessions. Examples: NetBIOS, RPC."},
  {q:"What is the network address for 192.168.10.75/27?",opts:["192.168.10.0","192.168.10.64","192.168.10.96","192.168.10.32"],a:1,d:"Subnetting",exp:"/27 = block size 32. 75÷32 = 2 remainder 11, so network = 2×32 = 64. Network: 192.168.10.64, Broadcast: 192.168.10.95, Hosts: .65–.94."},
  {q:"What does the term 'broadcast domain' mean?",opts:["All devices reachable by any IP","The set of devices that receive a Layer 2 broadcast frame","Only devices on the same physical switch","Devices sharing a single routing table"],a:1,d:"Switching",exp:"A broadcast domain is the set of devices that receive a broadcast frame (dest MAC FF:FF:FF:FF:FF:FF). Routers separate broadcast domains; switches don't."},
  {q:"Which protocol is used to synchronize clocks across network devices?",opts:["SNMP","Syslog","NTP","TFTP"],a:2,d:"Protocols",exp:"NTP (Network Time Protocol) synchronizes clocks to within milliseconds using a hierarchy of time servers. Accurate time is critical for logs, certificates and Kerberos."},
  {q:"What is the broadcast address for 192.168.5.0/25?",opts:["192.168.5.127","192.168.5.255","192.168.5.128","192.168.5.63"],a:0,d:"Subnetting",exp:"/25 = block 128. Network .0, broadcast = .0 + 128 − 1 = .127. Hosts: .1–.126 (126 usable)."},
  {q:"At which OSI layer does TLS/SSL encryption operate?",opts:["Layer 3 – Network","Layer 4 – Transport","Layer 6 – Presentation","Layer 7 – Application"],a:2,d:"OSI Model",exp:"TLS/SSL is defined at Layer 6 (Presentation) where data format, encryption and compression occur. Some models place it at Layer 4/7 depending on perspective."},
  {q:"What is the purpose of the Spanning Tree Protocol (STP)?",opts:["Encrypt switch-to-switch links","Prevent Layer 2 broadcast storms caused by switching loops","Assign VLANs to switch ports","Enable inter-VLAN routing"],a:1,d:"Switching",exp:"STP (802.1D) prevents loops in redundant switched topologies by putting certain ports in blocking state, allowing only a loop-free tree topology."}
],

/* ────────────────────────────────────────────────────────────
   COMPTIA NETWORK+ N10-009  (52 questions)
   Domains: Networking Concepts 23% | Infrastructure 22% |
            Network Operations 17% | Network Security 19% |
            Network Troubleshooting 19%
   ──────────────────────────────────────────────────────────── */
networkplus:[
  /* ── Networking Concepts ── */
  {q:"Which of the following describes a Software-Defined Network (SDN)?",opts:["A network that only uses wireless links","Separates the control plane from the data plane, managed by a centralized controller","A VPN that uses software tunnels only","A network with virtualized switches running in containers"],a:1,d:"Networking Concepts",exp:"SDN decouples the control plane (routing decisions) from the data plane (forwarding). A centralized controller programs forwarding rules across devices via APIs (e.g., OpenFlow)."},
  {q:"What is the purpose of a VXLAN?",opts:["Replace OSPF in data centres","Extend Layer 2 networks across Layer 3 infrastructure using UDP encapsulation","Encrypt VLAN traffic","Provide QoS for video conferencing"],a:1,d:"Networking Concepts",exp:"VXLAN (Virtual Extensible LAN) encapsulates Layer 2 frames in UDP datagrams, enabling large-scale virtual networks across routed data centre fabrics. Supports up to 16 million segment IDs."},
  {q:"Which protocol provides automatic failover for the default gateway by allowing multiple routers to share one virtual IP?",opts:["OSPF","VRRP or HSRP","STP","LACP"],a:1,d:"Networking Concepts",exp:"VRRP (IEEE standard) and HSRP (Cisco-proprietary) both provide First Hop Redundancy. Multiple physical routers share a virtual IP/MAC; hosts point to that virtual address."},
  {q:"What does 'contention-based access' mean in networking?",opts:["All devices get a guaranteed time slot to transmit","Devices compete for the shared medium — only one can transmit at a time","Devices must contact a central controller before sending","Encryption-based access using certificate contention"],a:1,d:"Networking Concepts",exp:"CSMA/CD (Ethernet) and CSMA/CA (Wi-Fi) are contention-based — devices listen before transmitting and handle collisions or use backoff algorithms."},
  {q:"Which protocol encapsulates IP packets for transport over MPLS networks?",opts:["GRE","MPLS uses label switching — IP packets are labelled, not re-encapsulated","IPSec","L2TP"],a:1,d:"Networking Concepts",exp:"MPLS adds a 32-bit label between Layer 2 and 3 headers. LSRs (label switch routers) forward based on labels, not IPs — faster and enables traffic engineering."},
  {q:"What is the functional difference between half-duplex and full-duplex?",opts:["Half-duplex is wired; full-duplex is wireless","Half-duplex allows only one direction at a time; full-duplex allows simultaneous bidirectional communication","Full-duplex uses twice the bandwidth","They are the same on modern switches"],a:1,d:"Networking Concepts",exp:"Half-duplex (collision possible — CSMA/CD needed) vs full-duplex (simultaneous TX/RX — no collisions, CSMA/CD not needed). Modern switched Ethernet is full-duplex."},
  {q:"In the context of cloud computing, what does IaaS provide?",opts:["Hosted software applications only","Virtualised compute, storage and networking on demand — the customer manages OS and above","A managed platform for deploying applications","Completed services like email or CRM"],a:1,d:"Networking Concepts",exp:"IaaS (Infrastructure as a Service) provides raw compute, storage and networking. The provider manages physical hardware; the customer controls OS, middleware and apps."},
  {q:"What is the purpose of a proxy server?",opts:["Assign IP addresses to clients","Act as an intermediary between clients and servers, caching content and filtering requests","Replace a firewall","Provide wireless access"],a:1,d:"Networking Concepts",exp:"A proxy server forwards client requests, can cache responses for speed, filter URLs, log activity and hide client IPs. Forward and reverse proxies serve different purposes."},
  {q:"What does a load balancer do?",opts:["Prevent routing loops","Distribute client requests across multiple backend servers to maximize availability and performance","Encrypt traffic between clients and servers","Assign VLAN tags"],a:1,d:"Networking Concepts",exp:"Load balancers (hardware or software, L4 or L7) distribute incoming requests using algorithms like round-robin, least-connections or IP hash."},
  {q:"What is the difference between latency and jitter?",opts:["They are the same thing","Latency is the total delay; jitter is the variation in that delay over time","Jitter is always higher than latency","Latency only affects video; jitter affects voice"],a:1,d:"Networking Concepts",exp:"Latency = delay (ms) from source to destination. Jitter = variance in latency over successive packets. Both matter for VoIP/video; high jitter causes choppy audio."},
  {q:"Which type of DNS record is used to map a hostname to an IPv6 address?",opts:["A record","AAAA record","PTR record","MX record"],a:1,d:"Networking Concepts",exp:"AAAA (quad-A) records map hostnames to IPv6 addresses. A records map to IPv4. PTR is reverse-lookup. MX identifies mail servers."},

  /* ── Infrastructure ── */
  {q:"A Cat6 cable is labeled '23 AWG'. What does AWG indicate?",opts:["The cable's maximum speed rating","American Wire Gauge — the thickness of the copper conductor (lower = thicker)","The cable shielding rating","The number of twisted pairs"],a:1,d:"Infrastructure",exp:"AWG (American Wire Gauge) measures wire diameter. Lower AWG = thicker wire = lower resistance = supports longer runs. Cat6 23 AWG vs Cat5e 24 AWG — slightly thicker."},
  {q:"What is the maximum distance for a standard multimode fiber (OM3) 10 Gigabit Ethernet link?",opts:["100m","300m","550m","10km"],a:1,d:"Infrastructure",exp:"OM3 multimode fiber supports 10GBase-SR up to 300 metres. OM4 extends this to 400m. Single-mode fiber (OS2) can reach 10km+ at 10Gbps."},
  {q:"Which connector type is most commonly used for Cat6 Ethernet cables?",opts:["ST","LC","RJ-45","BNC"],a:2,d:"Infrastructure",exp:"RJ-45 (8P8C) is the standard connector for Cat5e/6/6A UTP Ethernet. LC and ST are fiber connectors. BNC was used on coaxial cable."},
  {q:"What is 'Power over Ethernet' (PoE) and which standard delivers up to 30W per port?",opts:["A protocol that runs data over power lines — IEEE 802.3at (PoE+)","Transmitting data and DC power on the same cable — IEEE 802.3at (PoE+)","Wireless power — IEEE 802.11ah","An IP-based power management standard"],a:1,d:"Infrastructure",exp:"PoE allows switches to power devices (APs, phones, cameras) over Cat5e/6. 802.3af delivers 15.4W, 802.3at (PoE+) delivers 30W, 802.3bt (PoE++) up to 90W."},
  {q:"What is a 'collision domain'?",opts:["All devices on the same VLAN","A set of devices where a collision can occur when two devices transmit simultaneously","Every device reachable by a router","Devices that share an SSID"],a:1,d:"Infrastructure",exp:"In half-duplex Ethernet, all devices on a shared segment form a collision domain. Each switch port is its own collision domain; routers separate both collision and broadcast domains."},
  {q:"What does an optical OTDR (Optical Time-Domain Reflectometer) measure?",opts:["Wireless signal strength","Fiber cable length, splice loss, and fault location","Cable impedance","Copper pair crosstalk"],a:1,d:"Infrastructure",exp:"OTDR sends a laser pulse into fiber and measures reflections to find the distance to faults, connectors, splices and the end of the cable — essential for fiber troubleshooting."},
  {q:"Which 802.11 amendment introduced MU-MIMO and operates on 5 GHz only?",opts:["802.11n (Wi-Fi 4)","802.11ac (Wi-Fi 5)","802.11ax (Wi-Fi 6)","802.11g"],a:1,d:"Infrastructure",exp:"802.11ac (Wi-Fi 5) operates exclusively on 5 GHz, introduces MU-MIMO (multiple simultaneous spatial streams), beamforming and wider 80/160 MHz channels."},
  {q:"What is the purpose of a patch panel in a structured cabling system?",opts:["Power devices with PoE","Provide a central termination point for horizontal cable runs, allowing flexible cross-connection","Amplify signals over long runs","Provide wireless coverage"],a:1,d:"Infrastructure",exp:"A patch panel terminates permanent cable runs from wall jacks. Short patch cables connect specific ports to switches, making moves/adds/changes easy and organised."},
  {q:"What distinguishes a managed switch from an unmanaged switch?",opts:["Managed switches are always faster","A managed switch supports VLAN config, SNMP, port mirroring, STP — a unmanaged switch is plug-and-play only","Managed switches use fiber; unmanaged use copper","They are the same — 'managed' is just a marketing term"],a:1,d:"Infrastructure",exp:"Managed switches have a CLI/web UI supporting VLANs, STP, QoS, SNMP monitoring, port mirroring (SPAN), link aggregation, and security features like 802.1X."},
  {q:"What is the purpose of a DMZ in network design?",opts:["Zone where all internal servers are placed","A network segment housing public-facing services, isolated from the internal LAN by firewalls","A VLAN reserved for management traffic","A zone with no routing capability"],a:1,d:"Infrastructure",exp:"A DMZ (Demilitarized Zone) hosts services accessed from the internet (web, email, DNS). Two firewalls — or one with three interfaces — separate the DMZ from both internet and LAN."},

  /* ── Network Operations ── */
  {q:"What does SNMP stand for and what is its primary function?",opts:["Simple Network Management Protocol — monitors and manages network devices","Secure Network Monitor Protocol — encrypts management traffic","Simple Network Messaging Protocol — sends alerts","Standard Network Management Platform — a monitoring software suite"],a:0,d:"Network Operations",exp:"SNMP (UDP 161/162) collects device metrics and alerts. An NMS polls agents on devices for MIB data. Traps (162) send unsolicited alerts when thresholds are crossed."},
  {q:"What is the difference between SNMP v2c and v3?",opts:["v2c is faster; v3 is for WAN","v3 adds authentication (MD5/SHA) and encryption (DES/AES) — v2c uses only a community string","They are identical","v2c is Cisco only; v3 is vendor-neutral"],a:1,d:"Network Operations",exp:"SNMPv2c uses community strings (essentially plaintext passwords). SNMPv3 adds user-based security: authentication (HMAC-MD5/SHA) and optional privacy (AES/DES encryption)."},
  {q:"What does a syslog message priority '0' (Emergency) mean?",opts:["Informational only","System is unusable — the highest severity level","A debug message","Normal operation notification"],a:1,d:"Network Operations",exp:"Syslog severity levels 0–7: 0=Emergency, 1=Alert, 2=Critical, 3=Error, 4=Warning, 5=Notice, 6=Informational, 7=Debug. Lower = more severe."},
  {q:"What is the purpose of a 'baseline' in network operations?",opts:["A minimum security standard","A documented record of normal network performance used to identify deviations","A physical cable reference standard","A routing protocol convergence time"],a:1,d:"Network Operations",exp:"A baseline documents normal metrics (bandwidth, latency, CPU, traffic patterns). When something changes, comparing to baseline quickly reveals anomalies."},
  {q:"What does MTTR stand for?",opts:["Maximum Time To Respond","Mean Time To Repair — average time to restore a failed component or system","Minimum Threshold To Route","Multi-Tenant Routing Restriction"],a:1,d:"Network Operations",exp:"MTTR (Mean Time To Repair) measures average repair time. MTBF (Mean Time Between Failures) measures average time between failures. Both are key availability metrics."},
  {q:"What is a 'site survey' in wireless networking?",opts:["A legal review of network contracts","An assessment of RF environment, coverage, interference and AP placement before/after WLAN deployment","A review of switch configuration","A customer satisfaction survey"],a:1,d:"Network Operations",exp:"A wireless site survey maps signal strength, identifies interference sources (microwaves, cordless phones, neighbouring APs), determines optimal AP placement and channel assignment."},

  /* ── Network Security ── */
  {q:"What is 'port security' on a Cisco switch?",opts:["Blocking all incoming traffic on a port","Restricting which MAC addresses can connect to a switch port — violating MACs trigger an action","Encrypting switch-to-switch traffic","A firewall rule set applied per-port"],a:1,d:"Network Security",exp:"Port security limits the number and/or specific MAC addresses on a switch port. Violations can shut down the port (shutdown), drop frames (protect) or log+count (restrict)."},
  {q:"What attack does DHCP snooping protect against?",opts:["ARP spoofing","Rogue DHCP servers sending false IP configurations to clients","DNS cache poisoning","STP root bridge attacks"],a:1,d:"Network Security",exp:"DHCP snooping validates DHCP messages — only ports configured as 'trusted' (uplinks to real DHCP servers) can send DHCP Offers/ACKs. Untrusted ports block server responses."},
  {q:"What does Dynamic ARP Inspection (DAI) protect against?",opts:["DHCP exhaustion attacks","ARP spoofing and ARP poisoning — it validates ARP packets against the DHCP snooping binding table","OSPF route injection","STP topology changes"],a:1,d:"Network Security",exp:"DAI inspects ARP packets on untrusted ports and drops ARP replies with IP–MAC mappings that don't match the DHCP snooping binding table, preventing man-in-the-middle attacks."},
  {q:"Which type of attack overwhelms a system with traffic from many compromised sources?",opts:["Phishing","Distributed Denial of Service (DDoS)","SQL Injection","Man-in-the-Middle"],a:1,d:"Network Security",exp:"A DDoS attack uses a botnet to flood a target with traffic, exhausting bandwidth, CPU or connection tables. Mitigation includes scrubbing centres, rate limiting and anycast."},
  {q:"What is 802.1X used for?",opts:["VLAN tagging on trunk ports","Port-based Network Access Control — authenticates devices before granting network access","Spanning tree root election","QoS marking"],a:1,d:"Network Security",exp:"802.1X uses RADIUS to authenticate supplicants (clients) via an authenticator (switch/AP) before allowing network access. EAP carries credentials over the wired/wireless link."},
  {q:"What is a 'honeypot' in network security?",opts:["An encrypted password vault","A decoy system designed to attract attackers and study their behaviour without exposing real assets","A high-availability DNS server","A wireless access point for guest networks"],a:1,d:"Network Security",exp:"A honeypot mimics a vulnerable real system to lure attackers. It gathers intelligence on TTPs (tactics, techniques and procedures) while containing the attacker away from production."},
  {q:"Which protocol provides encrypted management access to network devices on port 22?",opts:["Telnet","HTTP","SSH","SNMP"],a:2,d:"Network Security",exp:"SSH (Secure Shell) encrypts management sessions. Telnet (port 23) and HTTP send credentials in cleartext. SSH supports password and public-key authentication."},
  {q:"What is NAC (Network Access Control)?",opts:["A protocol for IP address allocation","A framework that enforces security policy on devices before allowing them onto the network","A firewall type","A wireless authentication protocol"],a:1,d:"Network Security",exp:"NAC checks device health (patches, AV status, configuration compliance) before granting access. Non-compliant devices may be quarantined or given limited access."},

  /* ── Troubleshooting ── */
  {q:"A user reports 'limited connectivity' and their IP is 169.254.x.x. What is the most likely cause?",opts:["They have a static IP configured incorrectly","The DHCP server is unreachable — the device self-assigned an APIPA address","The DNS server is down","The default gateway is wrong"],a:1,d:"Troubleshooting",exp:"169.254.x.x = APIPA — the device could not reach a DHCP server. Check the DHCP server, network connectivity, and DHCP scope (is it exhausted?)."},
  {q:"Which command on a Windows PC displays the current ARP cache?",opts:["arp -a","ipconfig /displaydns","nslookup","netstat -r"],a:0,d:"Troubleshooting",exp:"'arp -a' shows the ARP cache (IP-to-MAC mappings). 'ipconfig /displaydns' shows cached DNS. 'netstat -r' shows the routing table. 'nslookup' queries DNS."},
  {q:"A user can ping the default gateway but cannot reach any external websites. What should you check first?",opts:["The user's NIC driver","DNS resolution — try pinging 8.8.8.8 to test IP connectivity without DNS","Replace the network cable","Reboot the switch"],a:1,d:"Troubleshooting",exp:"If ping to gateway works but no web access, try pinging a known IP (8.8.8.8). If that works, it's a DNS issue. If that fails, the problem is routing/firewall beyond the gateway."},
  {q:"What does the 'traceroute' (Windows: tracert) tool reveal?",opts:["Open ports on a remote host","Every router hop between source and destination along with RTT per hop","MAC addresses of each hop","DNS resolution path"],a:1,d:"Troubleshooting",exp:"Traceroute uses ICMP (Windows) or UDP/ICMP (Linux/Cisco) packets with incrementing TTL values. When TTL=0, each router returns an ICMP Time Exceeded, revealing the hop path."},
  {q:"You connect a laptop to a switch port and the link light does not come on. What is the FIRST thing to check?",opts:["Replace the switch","Check the cable, the correct port, and whether the NIC is enabled — follow the OSI model from Layer 1 up","Run 'ipconfig /renew'","Check DNS settings"],a:1,d:"Troubleshooting",exp:"No link light = Layer 1 problem. Start at Physical: cable seated correctly, correct cable type, cable not damaged, NIC enabled, switchport not shutdown. Use a cable tester."},
  {q:"A network technician runs 'show interfaces GigabitEthernet0/0' and sees 'line protocol is down'. The line status is 'up'. What does this indicate?",opts:["Physical cable fault","Layer 1 is working (cable connected) but Layer 2 protocol has failed — check encapsulation or keepalives","IP address is missing","The interface is shut down"],a:1,d:"Troubleshooting",exp:"'up/down' = physical link works, but Layer 2 failed. Common causes: mismatched encapsulation, missing keepalives on serial links, duplex mismatch, or WAN provider issue."},
  {q:"What does 'duplex mismatch' cause and how does it typically present?",opts:["Incorrect VLAN assignment","Slow performance and high collision/error counts — one end is full-duplex, the other is half-duplex","Complete loss of connectivity","DNS failures"],a:1,d:"Troubleshooting",exp:"A duplex mismatch (one port auto-negotiated to half, other set to full) causes late collisions on the half-duplex side and runts/giants errors. Performance degrades significantly under load."},
  {q:"Which tool would you use to capture and analyse raw network packets?",opts:["Ping","Wireshark (or similar packet analyser)","Traceroute","SNMP manager"],a:1,d:"Troubleshooting",exp:"Wireshark (and tcpdump) capture raw packets for deep analysis — viewing headers, payload, timing. Essential for diagnosing application-layer issues, misconfigurations and attacks."},
  {q:"A user on VLAN 10 cannot communicate with a user on VLAN 20. Both can reach their own default gateways. What is the most likely issue?",opts:["Wrong subnet mask","No inter-VLAN routing configured — a Layer 3 switch SVIs or router-on-a-stick is needed","STP is blocking their ports","DHCP scopes are wrong"],a:1,d:"Troubleshooting",exp:"VLANs are separate broadcast domains by design. Inter-VLAN communication requires a router or Layer 3 switch. Without routing, VLAN 10 and 20 cannot communicate."},
  {q:"What does the command 'nslookup google.com' do?",opts:["Pings google.com","Queries DNS to resolve google.com to its IP address","Tests HTTP connectivity","Shows the ARP entry for google.com"],a:1,d:"Troubleshooting",exp:"nslookup queries the configured DNS server for the IP of the specified hostname. Useful for diagnosing DNS failures — if it fails but ping to 8.8.8.8 works, DNS is the problem."},
  {q:"What is the purpose of a 'loopback test' on a network interface?",opts:["Test internet connectivity","Send test traffic out the NIC and back to verify the NIC and driver are working without a network connection","Check for cable faults","Test the DHCP server"],a:1,d:"Troubleshooting",exp:"A loopback test (IP 127.0.0.1 or physical loopback plug) verifies the NIC hardware and driver are functional independent of any external cable or network."}
],

/* ────────────────────────────────────────────────────────────
   CISCO CCNA 200-301  (52 questions)
   Domains: Network Fundamentals 20% | Network Access 20% |
            IP Connectivity 25% | IP Services 10% |
            Security Fundamentals 15% | Automation 10%
   ──────────────────────────────────────────────────────────── */
ccna:[
  /* ── Network Fundamentals ── */
  {q:"What is the administrative distance of EIGRP on a Cisco router?",opts:["90 (internal), 170 (external)","100","110","120"],a:0,d:"Network Fundamentals",exp:"EIGRP internal routes have AD 90, external routes AD 170. OSPF = 110, RIP = 120, directly connected = 0, static = 1. Lower AD = more trustworthy."},
  {q:"Which command displays a summary of all interfaces, including IP address and line/protocol status?",opts:["show interfaces","show ip route","show ip interface brief","show running-config"],a:2,d:"Network Fundamentals",exp:"'show ip interface brief' (sh ip int bri) gives a compact table: interface name, IP, OK?, method, status (line) and protocol. Fastest way to check all interfaces at once."},
  {q:"What does the 'no shutdown' command do on a Cisco router interface?",opts:["Removes the IP address","Enables a previously disabled interface","Resets the interface counters","Deletes the interface config"],a:1,d:"Network Fundamentals",exp:"Router interfaces are administratively down by default. 'no shutdown' enables them. Switch access ports are up by default. Check status with 'show ip interface brief'."},
  {q:"What is a 'stub network' in routing?",opts:["A network with only one exit point — traffic to/from it must use that one path","A network that uses static routes only","A network with no routers","A network running RIP"],a:0,d:"Network Fundamentals",exp:"A stub network has only one path in/out. It doesn't need to run a full routing protocol — a default route pointing out usually suffices, reducing protocol overhead."},
  {q:"Which encapsulation type is used on Cisco serial interfaces by default?",opts:["PPP","Frame Relay","HDLC (Cisco proprietary)","Ethernet"],a:2,d:"Network Fundamentals",exp:"Cisco serial interfaces default to HDLC (Cisco's proprietary version). When connecting to non-Cisco equipment, PPP is used (open standard). Set with 'encapsulation ppp'."},
  {q:"How many host addresses are available in a /22 subnet?",opts:["510","1022","2046","4094"],a:2,d:"Network Fundamentals",exp:"/22 has 10 host bits (32-22=10): 2^10 = 1024 total addresses, minus 2 (network + broadcast) = 1022 usable hosts."},
  {q:"What is the purpose of the 'ip default-gateway' command on a Cisco switch?",opts:["Configure routing between VLANs","Define the gateway for management traffic when the switch has no routing capability","Enable OSPF on the switch","Set the native VLAN"],a:1,d:"Network Fundamentals",exp:"On a Layer 2 switch, 'ip default-gateway' sets where to send management traffic (SSH, SNMP, ping) destined outside the management VLAN's subnet."},
  {q:"What is Cisco Express Forwarding (CEF)?",opts:["A routing protocol for ISPs","A Layer 3 switching mechanism using FIB and adjacency tables for wire-speed forwarding without route cache dependency","An encryption protocol","A QoS marking method"],a:1,d:"Network Fundamentals",exp:"CEF pre-builds two tables: the FIB (Forwarding Information Base, derived from routing table) and the Adjacency Table (Layer 2 next-hop info). Packets are forwarded at hardware speed."},

  /* ── Network Access ── */
  {q:"What is the purpose of an 802.1Q trunk port?",opts:["Carry traffic for a single VLAN only","Carry traffic for multiple VLANs simultaneously by tagging frames with a VLAN ID","Connect a PC to a switch","Provide PoE to IP phones"],a:1,d:"Network Access",exp:"802.1Q trunks insert a 4-byte tag into the Ethernet frame carrying the 12-bit VLAN ID. Trunks connect switches to other switches or routers to carry multiple VLANs on one link."},
  {q:"What happens to untagged frames arriving on a trunk port?",opts:["They are dropped","They are assigned to the native VLAN","They trigger a security violation","They are sent to all VLANs"],a:1,d:"Network Access",exp:"Untagged frames on a trunk are assumed to belong to the native VLAN (VLAN 1 by default). Best practice is to change the native VLAN and ensure both ends match to prevent attacks."},
  {q:"Which Spanning Tree variant is the IEEE standard for rapid convergence?",opts:["STP (802.1D)","RSTP (802.1W)","MSTP (802.1S)","PVST+"],a:1,d:"Network Access",exp:"RSTP (Rapid Spanning Tree Protocol, 802.1W) converges in under 1 second vs STP's ~50 seconds. MSTP (802.1S) maps multiple VLANs to STP instances. PVST+ is Cisco's per-VLAN STP."},
  {q:"What determines which switch becomes the STP root bridge?",opts:["The switch with the most ports","The switch with the lowest Bridge ID (Priority + MAC address)","The switch with the fastest uplink","The first switch to boot"],a:1,d:"Network Access",exp:"Bridge ID = priority (default 32768) + MAC address. The switch with the lowest Bridge ID is elected root bridge. Set with 'spanning-tree vlan X priority Y' (values must be multiples of 4096)."},
  {q:"What does the command 'switchport trunk encapsulation dot1q' configure?",opts:["Sets the native VLAN","Sets 802.1Q as the trunk encapsulation method — required before 'switchport mode trunk' on older IOS","Enables RSTP","Creates a VLAN"],a:1,d:"Network Access",exp:"On older Catalyst switches supporting both ISL and 802.1Q, you must specify encapsulation before configuring trunk mode. Newer switches only support dot1q and don't require this command."},
  {q:"What is an 'access port' on a Cisco switch?",opts:["A port that carries multiple VLANs","A port that carries traffic for a single VLAN and connects to an end device","A port used for management only","An uplink port to a router"],a:1,d:"Network Access",exp:"Access ports carry traffic for one VLAN without tagging. Configure with 'switchport mode access' and 'switchport access vlan X'. Frames leave to the end device untagged."},
  {q:"What does EtherChannel (LACP/PAgP) provide?",opts:["Layer 3 routing between switches","Combines multiple physical links into one logical link for increased bandwidth and redundancy","VLAN encryption","Wireless link aggregation"],a:1,d:"Network Access",exp:"EtherChannel (IEEE 802.3ad/LACP or Cisco PAgP) bundles 2–8 physical links. Traffic load-balances across all links. If one physical link fails, others continue — no STP topology change."},
  {q:"On a Cisco switch, what does 'spanning-tree portfast' do?",opts:["Disable STP on the port permanently","Allow the port to immediately enter the forwarding state, bypassing the listening/learning delay — for access ports only","Force the port to become root","Enable RSTP features"],a:1,d:"Network Access",exp:"PortFast skips the 30-second Listening+Learning delay for ports connected to end devices (PCs, printers), allowing immediate connectivity. Never enable on ports connected to switches."},
  {q:"What is BPDU Guard and when should it be used?",opts:["Prevents broadcast storms","Shuts down a PortFast-enabled port if it receives a BPDU — protects against rogue switches being connected","Encrypts BPDUs","Filters BPDU on trunk ports"],a:1,d:"Network Access",exp:"BPDU Guard errdisables a port immediately if a BPDU is received on it. Combine with PortFast on access ports — if someone connects a switch, the port shuts down preventing topology disruption."},

  /* ── IP Connectivity ── */
  {q:"Which OSPF packet type is used to discover and maintain neighbour relationships?",opts:["DBD (Database Description)","LSU (Link State Update)","Hello","LSAck"],a:2,d:"IP Connectivity",exp:"OSPF Hello packets are sent periodically (10s on broadcast, 30s on NBMA) to discover neighbours and verify they're still alive. Neighbours must share subnet, area, hello/dead timers."},
  {q:"What is an OSPF 'DR' (Designated Router) and why is it needed?",opts:["The router with the highest routing table","Elected on multi-access networks (Ethernet) to reduce LSA flooding — all OSPF routers form adjacency only with the DR/BDR","The router with lowest OSPF cost","The root bridge for OSPF networks"],a:1,d:"IP Connectivity",exp:"On broadcast segments, OSPF elects a DR (and BDR backup). Instead of n(n-1)/2 adjacencies, all routers only sync with DR/BDR — drastically reducing LSA traffic on large segments."},
  {q:"What determines OSPF's metric (cost)?",opts:["Hop count","Delay and bandwidth (like EIGRP)","100 Mbps ÷ interface bandwidth","Round-trip time"],a:2,d:"IP Connectivity",exp:"OSPF cost = reference bandwidth ÷ interface bandwidth. Default reference = 100 Mbps. FastEthernet cost = 1, Serial T1 = 64. Change reference with 'auto-cost reference-bandwidth 1000' for GbE."},
  {q:"What is the OSPF 'wildcard mask' and how does it differ from a subnet mask?",opts:["They are identical","A wildcard mask is the inverse of the subnet mask — 0 bits match, 1 bits are ignored","A wildcard mask uses decimal instead of binary","Wildcard masks only work with EIGRP"],a:1,d:"IP Connectivity",exp:"Wildcard mask = inverse of subnet mask (255.255.255.0 → 0.0.0.255). In OSPF 'network' statements, 0=must match, 1=don't care. Calculate: 255.255.255.255 − subnet mask."},
  {q:"Which type of route has the lowest administrative distance and highest preference?",opts:["Static route (AD 1)","OSPF (AD 110)","Directly connected (AD 0)","RIP (AD 120)"],a:2,d:"IP Connectivity",exp:"Directly connected routes (AD 0) are the most trusted — the router has a direct physical connection. Static routes are AD 1. EIGRP internal = 90. OSPF = 110. RIP = 120."},
  {q:"What command adds a default route on a Cisco router pointing to 10.0.0.1?",opts:["ip route 0.0.0.0 0.0.0.0 10.0.0.1","ip route default 10.0.0.1","ip default-route 10.0.0.1","route add default 10.0.0.1"],a:0,d:"IP Connectivity",exp:"'ip route 0.0.0.0 0.0.0.0 [next-hop]' is the IOS syntax for a default route (quad-zero route). It matches any destination not found in more specific routes."},
  {q:"What does 'convergence' mean in routing?",opts:["When all routers in the network have the same, accurate and consistent routing information","When OSPF elects a DR","When a router clears its routing table","When BGP accepts a route"],a:0,d:"IP Connectivity",exp:"Convergence is when all routers agree on the network topology. After a change (link failure, new network), routers exchange updates and re-converge. Faster convergence = less downtime."},
  {q:"In a 'router-on-a-stick' setup, where are the subinterfaces configured?",opts:["On the switch","On the router's physical interface, creating logical sub-interfaces for each VLAN with 802.1Q encapsulation","On a Layer 3 switch SVI","On the firewall"],a:1,d:"IP Connectivity",exp:"Router-on-a-stick: one physical router interface connects to a trunk port. Subinterfaces (e.g., Gi0/0.10, Gi0/0.20) each encapsulate a VLAN and have an IP for inter-VLAN routing."},
  {q:"What does 'ip route 192.168.2.0 255.255.255.0 Null0' accomplish?",opts:["Drops all traffic to 192.168.2.0/24 — used to prevent routing loops in summarisation","Creates a default route","Forwards to the null interface which amplifies traffic","Sets up a loopback test"],a:0,d:"IP Connectivity",exp:"Null0 is a virtual interface that discards all traffic silently. Used with route summarisation: the summary route points out, and the Null0 route prevents subnet traffic from matching the default route."},

  /* ── IP Services ── */
  {q:"What is the purpose of 'ip helper-address' on a Cisco router interface?",opts:["Set the default gateway","Forward DHCP broadcast requests as unicast to a DHCP server on another subnet","Enable routing on the interface","Configure DNS forwarder"],a:1,d:"IP Services",exp:"DHCP Discover is a broadcast (Layer 2) — it won't cross a router. 'ip helper-address [DHCP server IP]' on the router's interface converts the broadcast to a directed unicast, forwarding it to the DHCP server."},
  {q:"What is the difference between Static NAT and PAT (NAT Overload)?",opts:["They are identical","Static NAT maps one private IP to one public IP permanently; PAT maps many private IPs to one public IP using port numbers","PAT is more secure than static NAT","Static NAT requires dynamic routing"],a:1,d:"IP Services",exp:"Static NAT = one-to-one permanent mapping (needed for servers). PAT (Port Address Translation / NAT Overload) maps many private IPs to one public IP, differentiating sessions by unique port numbers."},
  {q:"What are the two modes of NTP operation?",opts:["Master and Slave","Server/client (NTP server provides time; client synchronises to it) and peer (both sync to each other)","Active and Passive","Primary and Secondary"],a:1,d:"IP Services",exp:"NTP client mode: the device synchronises to an NTP server. Peer mode: two devices cross-synchronise. Cisco: 'ntp server [ip]' makes the device a client; 'ntp master' makes it an NTP server."},
  {q:"What does SNMP OID stand for?",opts:["Operational Interface Descriptor","Object Identifier — a unique numeric path in the MIB tree identifying a specific managed object","Outbound Interface Data","Optical Interface Device"],a:1,d:"IP Services",exp:"An OID (e.g., 1.3.6.1.2.1.1.5.0) uniquely identifies a MIB variable. Network management systems query specific OIDs to retrieve device metrics like CPU, memory or interface counters."},

  /* ── Security Fundamentals ── */
  {q:"What does a standard IP access control list (ACL) filter on?",opts:["Source and destination IP, protocol and port","Source IP address only","Destination IP address only","Source MAC address"],a:1,d:"Security Fundamentals",exp:"Standard ACLs (numbered 1–99, 1300–1999) filter only on source IP. Extended ACLs (100–199, 2000–2699) filter on source/destination IP, protocol and port. Place standard ACLs close to the destination."},
  {q:"Where should an extended ACL be placed for best practice?",opts:["As close to the destination as possible","As close to the source as possible to stop unwanted traffic early","On the core switch only","On the firewall only"],a:1,d:"Security Fundamentals",exp:"Extended ACLs should be placed as close to the SOURCE as possible — they have enough specificity (source/dest/port) to make precise decisions and should stop traffic before it travels the network."},
  {q:"What does 'switchport port-security maximum 1' configure?",opts:["Allows any MAC to connect indefinitely","Allows only ONE MAC address on this port at a time","Sets the port speed to 1Mbps","Enables 802.1X on the port"],a:1,d:"Security Fundamentals",exp:"Port security with maximum 1 restricts the port to a single learned MAC. If a second device connects, the violation action (shutdown/restrict/protect) triggers."},
  {q:"What is the effect of the implicit 'deny any' at the end of every ACL?",opts:["Permits all traffic not explicitly matched","Denies all traffic not explicitly matched by earlier permit or deny statements","Logs all unmatched traffic","Resets the interface"],a:1,d:"Security Fundamentals",exp:"Every Cisco ACL ends with an invisible 'deny any'. If traffic doesn't match any explicit entry, it's dropped. Always add 'permit any' or specific permits before applying an ACL if needed."},
  {q:"What is the purpose of a 'login banner' (banner motd) on a Cisco device?",opts:["Show the hostname","Display a legal warning to users before they can log in — important for prosecution of unauthorized access","Speed up login time","Configure authentication"],a:1,d:"Security Fundamentals",exp:"A 'message of the day' banner informs users they're accessing a restricted system. Without a warning, courts may dismiss cases because users weren't notified the access was unauthorized."},
  {q:"What does 'service password-encryption' do on a Cisco device?",opts:["Enables AES-256 password encryption","Applies Cisco type 7 (weak Vigenère cipher) encryption to plaintext passwords in the running config","Enables SSH only","Disables Telnet"],a:1,d:"Security Fundamentals",exp:"Type 7 encryption is weak — easily reversed with free tools. Use 'enable secret' (MD5/Type 5) or 'enable algorithm-type sha256 secret' (Type 8/9) for strong password protection."},
  {q:"What is 'control plane policing' (CoPP) on a Cisco router?",opts:["Encrypts routing protocol updates","Rate-limits traffic destined to the router's CPU to protect against DoS attacks targeting the control plane","A type of QoS for user traffic","A feature that controls VLAN membership"],a:1,d:"Security Fundamentals",exp:"CoPP protects the router's CPU (control plane) from excessive traffic — whether malicious or accidental. It applies policy-maps to classify and police traffic hitting the router itself (OSPF, SSH, pings)."},

  /* ── Automation & Programmability ── */
  {q:"In network automation, what is a REST API?",opts:["A routing protocol for cloud networks","A software interface using HTTP methods (GET, POST, PUT, DELETE) to programmatically manage network devices","A type of VPN","A Cisco IOS feature for scripting"],a:1,d:"Automation",exp:"REST APIs use standard HTTP methods over HTTPS to read/modify device config programmatically. Cisco DNA Center, NSO and ACI all expose REST APIs. Responses are typically JSON or XML."},
  {q:"What data format is most commonly used with REST APIs in network automation?",opts:["YAML","XML","JSON","CSV"],a:2,d:"Automation",exp:"JSON (JavaScript Object Notation) is the dominant format for REST API requests/responses in networking. It's lightweight, human-readable and natively parsed by Python and most languages."},
  {q:"What does NETCONF use as its underlying protocol and what format does it use for data?",opts:["HTTP and JSON","SSH (port 830) and XML","Telnet and YAML","HTTPS and CSV"],a:1,d:"Automation",exp:"NETCONF (RFC 6241) runs over SSH (port 830). It uses XML for data modelling and RPC operations. YANG models define the data structure. RESTCONF is the HTTP equivalent."},
  {q:"What is Ansible in the context of network automation?",opts:["A Cisco-proprietary CLI scripting tool","An agentless open-source automation tool that uses YAML playbooks to configure network devices over SSH","A monitoring platform","A Python library for Cisco devices"],a:1,d:"Automation",exp:"Ansible uses YAML playbooks and requires no agent on managed devices (agentless). It communicates over SSH. Network modules exist for Cisco IOS, NXOS, Juniper, Arista, etc."},
  {q:"What is the purpose of a YANG model in network automation?",opts:["A Cisco scripting language","A data modelling language that defines the structure and constraints of configuration and operational data","A type of packet format","A routing protocol for SDN"],a:1,d:"Automation",exp:"YANG (Yet Another Next Generation) models define the schema for network device data. NETCONF/RESTCONF use YANG models to ensure correct data structure when reading or modifying config."},
  {q:"What is the difference between an 'imperative' and 'declarative' approach to network automation?",opts:["They are the same","Imperative specifies HOW to achieve a state (step-by-step); declarative specifies WHAT desired state should be and lets the system figure out HOW","Imperative is faster","Declarative requires more scripting"],a:1,d:"Automation",exp:"Imperative (e.g., scripted IOS commands) = step-by-step instructions. Declarative (e.g., Ansible, Terraform, Cisco NSO) = define desired end state; the tool calculates and applies changes."}
],

/* ────────────────────────────────────────────────────────────
   COMPTIA SECURITY+ SY0-701  (53 questions)
   Domains: General Security 12% | Threats & Attacks 22% |
            Security Architecture 18% | Security Operations 28% |
            Governance & Compliance 20%
   ──────────────────────────────────────────────────────────── */
securityplus:[
  /* ── General Security Concepts ── */
  {q:"What are the three components of the CIA triad, and what does each protect?",opts:["Confidentiality (data from unauthorised access), Integrity (data from unauthorised modification), Availability (systems accessible when needed)","Confidentiality, Isolation, Authentication","Ciphering, Integrity, Access","Control, Identification, Auditing"],a:0,d:"General Security",exp:"CIA: Confidentiality = only authorised parties access data. Integrity = data is accurate and unmodified. Availability = systems and data are accessible when needed. All three must be balanced."},
  {q:"What is 'non-repudiation' in information security?",opts:["Preventing data modification","The assurance that a party cannot deny having performed a specific action — proven through digital signatures and audit logs","Encrypting data at rest","Blocking unauthorized access"],a:1,d:"General Security",exp:"Non-repudiation proves an action occurred and who performed it. Digital signatures (using the sender's private key) and audit logs provide non-repudiation. Critical for legal and financial systems."},
  {q:"What is the difference between authentication and authorisation?",opts:["They are the same thing","Authentication verifies WHO you are; authorisation determines WHAT you're permitted to do","Authentication is Layer 7; authorisation is Layer 3","Authorisation happens before authentication"],a:1,d:"General Security",exp:"Authentication = identity verification (password, biometric, certificate). Authorisation = access control after identity is confirmed (RBAC, ACL, policies). Always in that order."},
  {q:"What does AAA stand for in security?",opts:["Authentication, Authorisation, Accounting","Access, Audit, Accountability","Authentication, Administration, Authorisation","Asymmetric, Authentication, Auditing"],a:0,d:"General Security",exp:"AAA: Authentication (prove identity), Authorisation (enforce access control), Accounting (track actions for billing/audit). RADIUS and TACACS+ are AAA protocols."},
  {q:"What is the difference between a vulnerability, a threat and a risk?",opts:["They are synonyms","A vulnerability is a weakness; a threat exploits vulnerabilities; risk = likelihood × impact","A threat is a known attack; vulnerability is theoretical","Risk is always 100% when a vulnerability exists"],a:1,d:"General Security",exp:"Vulnerability = weakness (unpatched software). Threat = a potential cause of an incident (attacker, malware). Risk = likelihood that a threat exploits a vulnerability × the business impact."},
  {q:"What is 'defence in depth'?",opts:["A single very strong perimeter firewall","Layering multiple independent security controls so compromising one layer doesn't compromise all","A military strategy only","Using the deepest encryption available"],a:1,d:"General Security",exp:"Defence in depth (layered security) means no single control is relied upon. Examples: perimeter firewall + IDS + endpoint AV + MFA + data encryption + user training. Each layer compensates for others' weaknesses."},
  {q:"What is the principle of least privilege?",opts:["Give all users admin rights to maximise productivity","Grant users and processes only the minimum permissions required to perform their specific job — no more","Only privileged users may use the internet","Restrict data access to the fewest possible servers"],a:1,d:"General Security",exp:"Least privilege limits blast radius — a compromised low-privilege account or process can't access critical data. Implement via RBAC, and regularly review/revoke unnecessary permissions."},

  /* ── Threats, Vulnerabilities & Mitigations ── */
  {q:"What is a 'zero-day' vulnerability?",opts:["A vulnerability found on the first day of deployment","An unknown vulnerability with no available patch — attackers can exploit it before the vendor is aware","A vulnerability with a CVSS score of 0","A flaw that only exists for 24 hours"],a:1,d:"Threats & Attacks",exp:"Zero-days are the most dangerous — no patch exists. Defences include network segmentation, anomaly detection, application whitelisting and behaviour-based endpoint protection since signature-based AV won't detect it."},
  {q:"What distinguishes ransomware from other malware?",opts:["It only attacks servers","It encrypts victim files and demands payment for the decryption key","It deletes files permanently","It steals data silently without disruption"],a:1,d:"Threats & Attacks",exp:"Ransomware encrypts files or systems and extorts payment. Modern 'double extortion' attacks also steal data before encrypting. Prevention: offline backups, patching, EDR, user training."},
  {q:"What is a 'watering hole' attack?",opts:["Flooding a server with HTTP requests","Compromising a website frequently visited by the target group — when targets visit, malware is delivered","A physical security attack near a water source","An attack on IoT sensors monitoring water systems"],a:1,d:"Threats & Attacks",exp:"Instead of attacking the target directly, attackers compromise websites the target regularly visits. When the target browses the site, drive-by download malware is installed silently."},
  {q:"What is the difference between a worm and a Trojan horse?",opts:["They are identical","A worm self-replicates and spreads across networks autonomously; a Trojan disguises itself as legitimate software to trick a user into installing it","A worm is a network attack; a Trojan is a physical attack","Trojans are legal; worms are not"],a:1,d:"Threats & Attacks",exp:"Worm: self-propagating, no host file, spreads via network vulnerabilities. Trojan: requires user action to install, appears legitimate, gives attacker backdoor access. Neither replicates like a virus needs a host file."},
  {q:"What is a 'credential stuffing' attack?",opts:["Physical theft of password books","Automated use of known username/password pairs (from previous breaches) against other services, exploiting password reuse","Brute-forcing passwords one at a time","Phishing for credentials via fake login pages"],a:1,d:"Threats & Attacks",exp:"Credential stuffing exploits password reuse — billions of credentials from prior breaches are tested against banks, email etc. MFA and unique passwords per site are the primary defences."},
  {q:"What is a 'supply chain attack'?",opts:["Attacking logistics companies physically","Compromising software or hardware before it reaches the target — via a trusted vendor, update mechanism or hardware component","Denial of service against e-commerce systems","SQL injection against shopping websites"],a:1,d:"Threats & Attacks",exp:"Supply chain attacks target the development/distribution pipeline. Example: SolarWinds — attackers injected malicious code into a software update that was then distributed to thousands of organisations."},
  {q:"What is SQL injection and how is it mitigated?",opts:["A network-layer attack — mitigated by firewalls only","Inserting malicious SQL into user inputs to manipulate database queries — mitigated by parameterised queries/prepared statements and input validation","A type of DDoS attack","An encryption weakness in SQL Server"],a:1,d:"Threats & Attacks",exp:"SQL injection manipulates database queries by inserting SQL code via input fields. Parameterised queries (prepared statements) prevent this by treating all user input as data, never as executable code."},
  {q:"What is cross-site scripting (XSS)?",opts:["A network scanning technique","Injecting malicious scripts into web pages viewed by other users — allowing session theft, credential harvesting or malware delivery","A type of SQL attack","A server-side code injection flaw"],a:1,d:"Threats & Attacks",exp:"XSS injects malicious JavaScript into pages. Stored XSS persists in the database. Reflected XSS is in URL parameters. DOM-based XSS is client-side. Mitigate: input sanitisation, Content Security Policy headers."},
  {q:"What is a 'man-in-the-middle' (MitM) attack?",opts:["An attacker physically positioned between two computers","An attacker secretly intercepts and potentially alters communications between two parties who believe they're communicating directly","An attack using two compromised hosts","A DoS attack from multiple sources"],a:1,d:"Threats & Attacks",exp:"MitM enables eavesdropping and data modification. ARP poisoning and HTTPS downgrade attacks are common vectors. Mitigate: mutual TLS, certificate pinning, HSTS, end-to-end encryption."},
  {q:"What is 'vishing'?",opts:["Phishing via video calls","Voice phishing — social engineering via telephone calls to extract sensitive information","A type of malware spread via VoIP","Phishing specifically targeting VPN users"],a:1,d:"Threats & Attacks",exp:"Vishing uses phone calls — attackers impersonate banks, tech support, or government agencies to extract credentials, OTPs or financial information. Smishing = SMS phishing."},
  {q:"What is a 'Business Email Compromise' (BEC) attack?",opts:["Malware sent via email attachments","Fraudulent emails impersonating executives or vendors to authorise wire transfers or sensitive data disclosure","A ransomware delivered by email","A technique to harvest email credentials"],a:1,d:"Threats & Attacks",exp:"BEC is one of the costliest attack types. Attackers compromise or spoof executive email accounts, then instruct employees to urgently transfer funds or send data. No malware involved — pure social engineering."},

  /* ── Security Architecture ── */
  {q:"What is 'Zero Trust' architecture?",opts:["A network with no external connections","A security model that eliminates implicit trust — every access request is verified regardless of network location, following 'never trust, always verify'","A network design using no firewalls","A guest network with zero access"],a:1,d:"Security Architecture",exp:"Zero Trust assumes breach — users, devices and applications must continuously prove they should have access. Based on principles: verify explicitly, least privilege, assume breach. Microsegmentation is key."},
  {q:"What is the purpose of a Next-Generation Firewall (NGFW)?",opts:["A firewall that only operates at Layer 7","Combines traditional stateful inspection with DPI, application awareness, user identity and integrated IPS — goes beyond port/protocol filtering","A cloud-only firewall","A hardware-based firewall with no software component"],a:1,d:"Security Architecture",exp:"NGFWs can identify applications (not just ports), enforce policies based on user identity, decrypt and inspect TLS, detect threats via integrated IPS signatures, and provide URL filtering."},
  {q:"What is microsegmentation?",opts:["Dividing a network into subnets smaller than /30","Granular security policy enforcement at the workload/application level within a data centre — limits lateral movement after a breach","A subnetting technique for IPv6","Segmenting wireless networks by SSID"],a:1,d:"Security Architecture",exp:"Microsegmentation uses firewalls or SDN policies between individual workloads (even in the same VLAN) to prevent an attacker from moving laterally after compromising one system."},
  {q:"What is data loss prevention (DLP)?",opts:["Backing up data to prevent loss","Technology that detects and prevents sensitive data (PII, financials, IP) from leaving the organisation via email, USB, web uploads etc.","Encrypting data at rest","A firewall feature that blocks large file transfers"],a:1,d:"Security Architecture",exp:"DLP monitors data in motion (network), data at rest (storage) and data in use (endpoints). It detects patterns like credit card numbers, SSNs and confidential keywords to block exfiltration."},
  {q:"What is a 'demilitarized zone' (DMZ)?",opts:["A zone with military-grade encryption only","A network segment hosting public-facing servers, isolated from the internal LAN by firewalls — if compromised, the LAN is still protected","A VLAN for decommissioned servers","A network segment with no security controls"],a:1,d:"Security Architecture",exp:"A DMZ sits between two firewalls (or one with three interfaces). Public services (web, email, DNS) live there. Even if an attacker compromises a DMZ server, they're still blocked from the internal network."},
  {q:"What does 'TLS certificate pinning' do?",opts:["Pins TLS certificates to physical servers","Hardcodes an expected certificate or public key into an application, rejecting any other certificate even from a trusted CA — prevents MitM with rogue certificates","A method for certificate auto-renewal","Encrypting the certificate with a PIN"],a:1,d:"Security Architecture",exp:"Certificate pinning defeats MitM attacks using fraudulently issued certificates from compromised CAs. Applications only accept a specific certificate/public key. Common in high-security mobile apps and APIs."},
  {q:"What is the purpose of a SIEM (Security Information and Event Management)?",opts:["A next-generation firewall","Aggregates and correlates log data from multiple sources to detect threats, generate alerts and provide forensic analysis","A data backup solution","An identity management platform"],a:1,d:"Security Architecture",exp:"SIEM (Splunk, IBM QRadar, Microsoft Sentinel) collects logs from firewalls, servers, endpoints and applications, correlates events across sources and generates alerts for SOC analysts."},
  {q:"What is 'public key infrastructure' (PKI)?",opts:["A network topology using public IP addresses","A framework of policies, roles, hardware and software to manage digital certificates and public/private key pairs — enabling encryption and authentication at scale","An authentication protocol like RADIUS","A file encryption tool"],a:1,d:"Security Architecture",exp:"PKI issues, manages, distributes, and revokes digital certificates (X.509). A Certificate Authority (CA) signs certificates. PKI underpins HTTPS, VPNs, code signing and email encryption (S/MIME)."},
  {q:"What is the difference between symmetric and asymmetric encryption?",opts:["Symmetric is newer and more secure","Symmetric uses ONE shared key for both encryption and decryption (fast); asymmetric uses a KEY PAIR (public+private) — slower but solves key distribution","Asymmetric is always used for bulk data","They use the same keys in different orders"],a:1,d:"Security Architecture",exp:"Symmetric (AES, ChaCha20) = fast, used for bulk data. Asymmetric (RSA, ECDH) = slower, solves key exchange. TLS uses asymmetric to exchange a symmetric session key — best of both."},
  {q:"What hashing algorithm is currently recommended for password storage?",opts:["MD5","SHA-1","bcrypt, Argon2, or PBKDF2 (slow, salted key-stretching algorithms)","SHA-256 without salting"],a:2,d:"Security Architecture",exp:"MD5 and SHA-1 are broken for passwords. SHA-256 is fast — attackers can compute billions of hashes/sec. bcrypt, Argon2 and PBKDF2 are specifically designed to be slow and memory-intensive, defeating GPU cracking."},
  {q:"What is the purpose of a digital signature?",opts:["Encrypt data so only the recipient can read it","Provide authenticity and non-repudiation — verifies the data came from the stated sender and hasn't been modified","Generate a shared encryption key","Store a digital certificate"],a:1,d:"Security Architecture",exp:"A digital signature uses the SENDER's PRIVATE key to sign (hash + encrypt). Recipient verifies with the sender's PUBLIC key. Proves identity and data integrity. Different from encryption (uses recipient's public key)."},

  /* ── Security Operations ── */
  {q:"What are the five phases of incident response (NIST SP 800-61)?",opts:["Plan, Protect, Detect, Respond, Recover","Preparation, Detection/Analysis, Containment, Eradication, Recovery (+ Post-Incident Activity)","Identify, Classify, Respond, Notify, Close","Alert, Triage, Escalate, Remediate, Document"],a:1,d:"Security Operations",exp:"NIST IR phases: 1) Preparation (training, tools, plans), 2) Detection & Analysis (identify & characterise), 3) Containment (limit damage), 4) Eradication (remove cause), 5) Recovery (restore), 6) Post-incident (lessons learned)."},
  {q:"What is the difference between an IDS and an IPS?",opts:["IDS blocks threats; IPS only detects","IDS detects and alerts on suspicious activity; IPS can also actively block malicious traffic inline","They are identical","IPS is a software-only solution"],a:1,d:"Security Operations",exp:"IDS (Intrusion Detection System) is passive — it monitors and alerts. IPS (Intrusion Prevention System) is inline — it can drop malicious packets in real time. NGFWs typically integrate IPS functionality."},
  {q:"What is 'threat hunting'?",opts:["Automated vulnerability scanning","Proactively and manually searching through networks and endpoints for advanced threats that evade automated detection","Running penetration tests","Monitoring firewall logs for known attack signatures"],a:1,d:"Security Operations",exp:"Threat hunting assumes attackers are already present and hidden. Hunters proactively search for indicators of compromise (IoCs) and tactics from frameworks like MITRE ATT&CK, going beyond alert-driven detection."},
  {q:"What is the purpose of a vulnerability scan vs. a penetration test?",opts:["They are identical","A vulnerability scan identifies potential weaknesses using automated tools; a penetration test actively attempts to exploit vulnerabilities to prove real-world impact","Pen tests are automated; scans are manual","Vulnerability scans require vendor permission; pen tests do not"],a:1,d:"Security Operations",exp:"Vuln scans (Nessus, Qualys, OpenVAS) find and prioritise weaknesses. Pen tests (authorised ethical hacking) verify exploitability and real business risk. Pen tests are more thorough and require clear scope/authorisation."},
  {q:"What does 'chain of custody' mean in digital forensics?",opts:["The physical chain used to secure servers","The documented record of who collected, handled, transferred and analysed evidence — ensuring admissibility in court","The encryption key hierarchy","The audit trail of firewall rules"],a:1,d:"Security Operations",exp:"Chain of custody documents every person who had access to evidence, when, and what they did. Breaks in chain of custody can make evidence inadmissible in legal proceedings."},
  {q:"What does EDR (Endpoint Detection and Response) provide?",opts:["Network firewall capabilities","Continuous monitoring, behavioural analysis and response capabilities on endpoints — detecting threats that evade traditional AV","Email security filtering","A VPN client"],a:1,d:"Security Operations",exp:"EDR (CrowdStrike, SentinelOne, Microsoft Defender for Endpoint) monitors endpoint behaviour, records telemetry for investigation, detects fileless malware and enables remote response actions (isolate, kill process, remediate)."},
  {q:"What is 'threat intelligence'?",opts:["A database of all known malware hashes","Actionable information about active threats — including attacker TTPs, IoCs, campaigns — used to inform defences and prioritise response","A SIEM configuration file","A type of penetration test"],a:1,d:"Security Operations",exp:"Threat intelligence (from ISACs, MISP, commercial feeds) provides context: who's attacking, how, and what to look for. STIX/TAXII are standards for sharing threat intelligence."},
  {q:"What does CVE/CVSS stand for, and what does a CVSS score represent?",opts:["Common Vulnerability Enumeration/Common Vulnerability Scoring System","Common Vulnerabilities and Exposures (CVE) is a dictionary of vulnerabilities; CVSS scores (0–10) quantify severity based on exploitability and impact","Critical Vulnerability Evaluation/Critical Vulnerability Security Score","Cisco Vulnerability Entry/Cisco Vulnerability Severity Score"],a:1,d:"Security Operations",exp:"CVE assigns unique IDs (e.g., CVE-2021-44228 = Log4Shell). CVSS scores from 0–10: 0–3.9 Low, 4–6.9 Medium, 7–8.9 High, 9–10 Critical. Factors: attack vector, complexity, privileges needed, impact."},
  {q:"What is 'credential harvesting'?",opts:["Backing up user passwords securely","Attacker techniques to collect valid credentials — via phishing, keyloggers, memory dumping (Mimikatz) or breach databases","Resetting all user passwords","The process of issuing certificates to users"],a:1,d:"Security Operations",exp:"Stolen credentials are the top initial access vector. Mimikatz extracts credentials from Windows memory. Keyloggers capture typing. MFA and privileged account protections limit damage from harvested credentials."},
  {q:"What is 'lateral movement' in the context of a cyber attack?",opts:["Moving servers physically between data centres","An attacker expanding access through a network after initial compromise — moving from one system to another to reach target data","Load balancing traffic across multiple servers","The movement of data between VLANs"],a:1,d:"Security Operations",exp:"After initial access, attackers move laterally using techniques like pass-the-hash, pass-the-ticket, RDP, SMB exploits or compromised credentials to reach high-value systems. Microsegmentation limits lateral movement."},

  /* ── Governance, Risk & Compliance ── */
  {q:"What does the NIST Cybersecurity Framework (CSF) consist of?",opts:["5 core functions: Identify, Protect, Detect, Respond, Recover","7 domains and 200+ controls","The CIA triad and three tiers of risk","ISO/IEC 27001 control domains"],a:0,d:"Governance & Compliance",exp:"NIST CSF core functions: Identify (assets, risks), Protect (safeguards), Detect (anomalies), Respond (incidents), Recover (restoration). Version 2.0 adds Govern. Widely used for risk management programmes."},
  {q:"What is a 'Business Impact Analysis' (BIA)?",opts:["An assessment of competitors","Identifies critical business processes and determines the impact of their disruption — outputs RTO, RPO and MAO","A financial audit","A review of data encryption standards"],a:1,d:"Governance & Compliance",exp:"BIA outputs: RTO (Recovery Time Objective — maximum acceptable downtime), RPO (Recovery Point Objective — max data loss), MAO (Maximum Allowable Outage). Drives BCP/DRP priorities."},
  {q:"What does GDPR primarily protect?",opts:["Corporate intellectual property","The personal data and privacy rights of EU/EEA residents — with strict rules on collection, processing, storage and breach notification","Critical national infrastructure","Classified government information"],a:1,d:"Governance & Compliance",exp:"GDPR (General Data Protection Regulation) applies to any organisation processing EU residents' data. Key requirements: lawful basis for processing, data minimisation, breach notification within 72 hours, right to erasure."},
  {q:"What is PCI-DSS?",opts:["A government security standard for military networks","Payment Card Industry Data Security Standard — mandatory requirements for organisations that store, process or transmit cardholder data","A European data privacy law","An ISO standard for information security management"],a:1,d:"Governance & Compliance",exp:"PCI-DSS (v4.0) has 12 requirements covering: network segmentation, encryption of cardholder data, access control, monitoring and regular testing. Non-compliance results in fines and loss of card processing rights."},
  {q:"What is the difference between a 'risk assessment' and a 'risk treatment'?",opts:["They are the same process","Risk assessment identifies and evaluates risks; risk treatment selects controls to modify (mitigate, transfer, accept or avoid) those risks","Risk treatment is done before assessment","Risk treatment means ignoring low-priority risks"],a:1,d:"Governance & Compliance",exp:"Risk management cycle: Identify assets → Identify threats/vulnerabilities → Assess risk (likelihood × impact) → Treat risk (mitigate via controls, transfer via insurance, accept as within tolerance, or avoid by changing business process)."},
  {q:"What is 'security awareness training' and why is it important?",opts:["Training for security engineers only","Educating ALL employees on threats (phishing, social engineering, safe data handling) — the human element is the most exploited attack vector","A certification programme for IT staff","A software tool that automatically teaches users"],a:1,d:"Governance & Compliance",exp:"95%+ of successful breaches involve human error. Effective security awareness training reduces phishing click rates, improves incident reporting and creates a security culture. Required by most compliance frameworks."}
]
};

window.TRACKS = [
  { id:"fundamentals", name:"Networking Fundamentals", icon:"📡", color:"var(--cyan)",   badge:"tb-blue",   qs:window.QUESTION_BANK.fundamentals, passScore:70, time:45, fullTime:30 },
  { id:"networkplus",  name:"CompTIA Network+ N10-009",icon:"🌐", color:"var(--green)",  badge:"tb-green",  qs:window.QUESTION_BANK.networkplus,  passScore:72, time:60, fullTime:90 },
  { id:"ccna",         name:"Cisco CCNA 200-301",       icon:"🔧", color:"var(--orange)", badge:"tb-orange", qs:window.QUESTION_BANK.ccna,         passScore:82, time:75, fullTime:120 },
  { id:"securityplus", name:"CompTIA Security+ SY0-701",icon:"🛡️", color:"var(--red)",   badge:"tb-red",    qs:window.QUESTION_BANK.securityplus, passScore:75, time:60, fullTime:90 }
];
})();
