/* =================================================================
   TEAM21 ACADEMY — TIME CAPSULE (Historical Notes)
   Each note: { year, title, text, icon }
   Attached into lessons by id reference.
   ================================================================= */

T21.history = {
  scratch_mit: { year:'2003', icon:'🎓', title:'Born at MIT', text:'Scratch began as a research project at the MIT Media Lab, led by Mitchel Resnick\'s "Lifelong Kindergarten Group." The goal: prove that ANY child could create with code, not just consume technology.' },
  scratch_growth: { year:'2007', icon:'🌍', title:'Scratch Goes Public', text:'Scratch 1.0 launched publicly. Today, over 100 million registered users and 130+ million shared projects make it the largest creative coding community for young people on Earth.' },
  logo_turtle: { year:'1967', icon:'🐢', title:'The Turtle That Started It All', text:'Decades before Scratch, Seymour Papert invented LOGO — a language where kids commanded a robotic "turtle" to draw shapes. LOGO proved children could think like programmers. Scratch and Python\'s "turtle" module both descend directly from this idea.' },
  ada_lovelace: { year:'1843', icon:'👑', title:'The First Programmer Was a Woman', text:'Ada Lovelace wrote notes on Charles Babbage\'s never-built "Analytical Engine" that included what historians call the first algorithm intended for a machine — over 100 years before electronic computers existed.' },
  grace_hopper: { year:'1952', icon:'⚓', title:'The First Compiler', text:'Rear Admiral Grace Hopper invented the compiler — software that translates human-readable code into machine instructions. Before her work, every program had to be written directly in binary. She also popularised the term "debugging" after finding an actual moth in a malfunctioning computer relay!' },
  python_xmas: { year:'1989', icon:'🎄', title:'Built Over Christmas Break',  text:'Guido van Rossum started writing Python during his Christmas holidays in 1989 as a side project to keep himself busy. He wanted a language that read like clear English. Today it\'s the most-taught programming language in the world.' },
  python_name: { year:'1991', icon:'🎬', title:'Why "Python"?', text:'Despite the snake logo, Python is named after the British comedy show "Monty Python\'s Flying Circus." Van Rossum was reading the show\'s scripts while choosing a name, and wanted his language to feel a little fun and irreverent.' },
  c_unix: { year:'1972', icon:'💻', title:'C and UNIX, Born Together', text:'Dennis Ritchie created C at Bell Labs specifically to rewrite the UNIX operating system. Before C, operating systems were written in assembly — tied to one specific machine. C let UNIX run on ANY hardware, which is why nearly every OS today (Linux, macOS, Windows internals) still owes its existence to C.' },
  c_kr_book: { year:'1978', icon:'📘', title:'The Most Influential Coding Book Ever', text:'"The C Programming Language" by Kernighan & Ritchie (nicknamed "K&R") is so foundational that experienced programmers still call C syntax conventions "K&R style" — almost 50 years later.' },
  cpp_name_joke: { year:'1985', icon:'😄', title:'A Programmer\'s Inside Joke', text:'Bjarne Stroustrup\'s language was nicknamed "C++" because in C, "++" means "increase by one." The name itself is a joke: C++ is literally "C, but one better."' },
  cpp_games: { year:'1993', icon:'🎮', title:'The Engine Behind Modern Games', text:'id Software\'s Doom (written largely in C, with some assembly) proved 3D gaming was possible on home PCs. Its successor engines moved to C++, and today nearly every AAA game engine — Unreal, Unity\'s core, CryEngine — is built on C++.' },
  java_oak: { year:'1991', icon:'🌳', title:'Originally Named After a Tree', text:'James Gosling\'s team at Sun Microsystems first called their new language "Oak," after a tree outside Gosling\'s office window. When they discovered the name was already trademarked, they renamed it Java — after the coffee the team drank constantly.' },
  java_applets: { year:'1995', icon:'🌐', title:'The Internet\'s First Interactive Language', text:'Java\'s original killer feature was "applets" — small programs that ran inside web browsers. Though applets are gone today, the "write once, run anywhere" philosophy they introduced still defines Java\'s use in Android and enterprise systems.' },
  js_10days: { year:'1995', icon:'⏱️', title:'Built in 10 Days', text:'Brendan Eich wrote the first version of JavaScript in just 10 days at Netscape, under pressure to ship before a deadline. Some of its quirks (like confusing type conversions) trace directly back to that rush — yet it became the most executed language on Earth.' },
  html_cern: { year:'1991', icon:'🔬', title:'Invented at a Physics Lab', text:'Tim Berners-Lee created HTML and the World Wide Web while working at CERN, the particle physics laboratory, to help scientists share documents. He gave the technology away for free — choosing not to patent it — which many credit as the reason the open web could flourish.' },
  css_1996: { year:'1996', icon:'🎨', title:'Solving "Browser Wars" Chaos', text:'Before CSS, web designers had to use messy workarounds (like invisible tables) just to control layout. Håkon Wium Lie proposed CSS specifically to separate content from design — ending years of inconsistent, hacky page styling.' },
  arduino_2005: { year:'2005', icon:'🔌', title:'Designed for Art Students', text:'Arduino was created in Italy by a team including Massimo Banzi, originally to give design students with NO electronics background an easy way to build interactive projects. That "easy for beginners" mission is why it remains the top choice for robotics education worldwide.' },
  raspi_2012: { year:'2012', icon:'🍓', title:'A $25 Computer for Every Kid', text:'The Raspberry Pi Foundation built a credit-card-sized, full computer that originally cost just $25 — created specifically to get inexpensive computing into schools after the founders noticed fewer students were studying computer science.' },
  ml_perceptron: { year:'1958', icon:'🧠', title:'The First "Neuron"', text:'Frank Rosenblatt built the Perceptron — the first artificial neural network — and it could be trained to recognise simple shapes. Newspapers at the time wildly overhyped it as a machine that could "walk, talk, see, write, reproduce itself." Reality took 60 more years to catch up.' },
  ml_ai_winter: { year:'1974–1980', icon:'❄️', title:'The First "AI Winter"', text:'Early AI promises went unfulfilled, funding dried up, and the field nearly stalled for years — a period researchers call an "AI winter." It happened again in the late 1980s. AI has died and been reborn several times before reaching today\'s breakthroughs.' },
  ml_deep_blue: { year:'1997', icon:'♟️', title:'Machine Beats World Champion', text:'IBM\'s Deep Blue defeated world chess champion Garry Kasparov — the first time a computer beat a reigning champion under tournament conditions. But Deep Blue used brute-force search, not learning; it couldn\'t do anything except play chess.' },
  ml_imagenet: { year:'2012', icon:'🖼️', title:'The Breakthrough Moment for Deep Learning', text:'A neural network called AlexNet shocked the AI world by dramatically outperforming every other approach at recognising images in the ImageNet competition. This single result convinced the entire field that "deep learning" was the future — and it triggered the AI boom we\'re still living through.' },
  ml_alphago: { year:'2016', icon:'⚫', title:'AI Conquers an "Impossible" Game', text:'Go was considered far too complex for computers — more possible positions than atoms in the universe. DeepMind\'s AlphaGo defeated world champion Lee Sedol 4 games to 1, partly by learning from millions of self-played games rather than being explicitly programmed with strategies.' },
  ml_transformer: { year:'2017', icon:'🔁', title:'The Paper That Changed Everything', text:'A Google research paper titled "Attention Is All You Need" introduced the Transformer architecture. It\'s the single most important AI breakthrough of the last decade — every major chatbot today, including Claude, ChatGPT, and Gemini, is built on Transformers.' },
  ml_gpt_chatgpt: { year:'2022', icon:'💬', title:'AI Reaches Everyone\'s Pocket', text:'ChatGPT reached 100 million users faster than any consumer application in history — just 2 months. It wasn\'t the first large language model, but it was the first one wrapped in an interface simple enough for anyone, of any age, to use immediately.' },
  ml_claude_constitutional: { year:'2022', icon:'🧭', title:'Teaching AI Right from Wrong — On Paper', text:'Anthropic, the company that builds Claude, pioneered an approach called "Constitutional AI" — training models using a written set of principles (a bit like a constitution) rather than only human feedback, aiming to make AI helpful AND safe by design.' },
  binary_leibniz: { year:'1703', icon:'🔢', title:'Binary Existed Before Computers', text:'Gottfried Leibniz formally described binary number systems over 300 years before the first electronic computer was built. He was inspired partly by ancient Chinese I Ching hexagrams. Every photo, song, and program you\'ve ever used is ultimately just patterns of his 1s and 0s.' },
  bug_moth: { year:'1947', icon:'🦋', title:'The Original "Bug"', text:'While the word "bug" for an error predates this event, Grace Hopper\'s team famously found an actual moth stuck in a relay of the Harvard Mark II computer, causing a malfunction. They taped the moth into the logbook with the note "first actual case of bug being found." That logbook still exists in a museum today.' },
};
